<?php
namespace Moss\component\reader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-29 at 14:23:08.
 */
class YAMLReaderTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var YAMLReader
	 */
	protected $object;

	protected $files = array(
		'1.yml' => array(0 => 'Mark McGwire', 1 => 'Sammy Sosa', 2 => 'Ken Griffey',),
		'2.yml' => array('hr' => 65, 'avg' => 0.278, 'rbi' => 147),
		'3.yml' => array(
			'american' => array(0 => 'Boston Red Sox', 1 => 'Detroit Tigers', 2 => 'New York Yankees'),
			'national' => array(0 => 'New York Mets', 1 => 'Chicago Cubs', 2 => 'Atlanta Braves')
		),
		'4.yml' => array(
			0 => array('name' => 'Mark McGwire', 'hr' => 65, 'avg' => 0.278),
			1 => array('name' => 'Sammy Sosa', 'hr' => 63, 'avg' => 0.288)
		),
		'5.yml' => array(
			0 => array(0 => 'name', 1 => 'hr', 2 => 'avg'),
			1 => array(0 => 'Mark McGwire', 1 => 65, 2 => 0.278),
			2 => array(0 => 'Sammy Sosa', 1 => 63, 2 => 0.288)
		),
//		'6.yml' => array(),
		'7.yml' => array(
			0 => array(0 => 'Mark McGwire', 1 => 'Sammy Sosa', 2 => 'Ken Griffey'),
			1 => array(0 => 'Chicago Cubs', 1 => 'St Louis Cardinals')
		),
		'8.yml' => array(
			0 => array('time' => '20:03:20', 'player' => 'Sammy Sosa', 'action' => 'strike (miss)'),
			1 => array('time' => '20:03:47', 'player' => 'Sammy Sosa', 'action' => 'grand slam')
		),
		'9.yml' => array(
			'hr' => array(0 => 'Mark McGwire', 1 => 'Sammy Sosa'),
			'rbi' => array(0 => 'Sammy Sosa', 1 => 'Ken Griffey')
		),
		'10.yml' => array(
			'hr' => array(0 => 'Mark McGwire', 1 => 'Sammy Sosa'),
			'rbi' => array(0 => 'Sammy Sosa', 1 => 'Ken Griffey')
		),
//		'11.yml' => array(),
		'12.yml' => array(
			0 => array('item' => 'Super Hoop', 'quantity' => 1),
			1 => array('item' => 'Basketball', 'quantity' => 4),
			2 => array('item' => 'Big Shoes', 'quantity' => 1)
		),
		'13.yml' => "\//||\/||\n// ||  ||__",
		'14.yml' => 'Mark McGwire\'s year was crippled by a knee injury.',
		'15.yml' => '> Sammy Sosa completed another fine season with great stats.  63 Home Runs 0.288 Batting Average  What a year!', // TODO - remove > at line start
		'16.yml' => array('name' => 'Mark McGwire', 'accomplishment' => "Mark set a major league home run record in 1998.\n", 'stats' => "65 Home Runs\n0.278 Batting Average\n"), // TODO - remove last line \n
//		'17.yml' => array(
//			'unicode' => 'Sosa did fine.\u263A',
//			'control' => "\\b1998\\t1999\\t2000\n",
//			'hex esc' => "\\x0d\\x0a is \n",
//			'single' => '"Howdy!" he cried.',
//			'quoted' => ' # Not a \'comment\'.',
//			'tie-fighter' => '|\-*-/|'
//		),
//		'18.yml' => array('plain' => "This unquoted scalar spans many lines.\n", 'quoted' => "So does this quoted scalar.\n"),
		'19.yml' => array('canonical' => 12345, 'decimal' => 12345, 'octal' => '0o14', 'hexadecimal' => 0,),
		'20.yml' => array('canonical' => 1230.15, 'exponential' => 1230.15, 'fixed' => 1230.15, 'negative infinity' => '-INF', 'not a number' => 'INF'),
		'21.yml' => array('' => '', 'booleans' => array('0' => true, '1' => false), 'string' => '012345'),
		'22.yml' => array('canonical' => 1008385183, 'iso8601' => 1008385183, 'spaced' => 1008385183, 'date' => 1039820400),
//		'23.yml' => array(),
//		'24.yml' => array(),
//		'25.yml' => array(),
		'26.yml' => array(
			0 => array('Mark McGwire' => 65),
			1 => array('Sammy Sosa' => 63),
			2 => array('Ken Griffy' => 58)
		),
		'27.yml' => array(
			'invoice' => 34843,
			'date' => 980204400,
			'bill-to' => array('given' => 'Chris', 'family' => 'Dumars', 'address' => array('lines' => "458 Walkman Dr.\nSuite #292\n", 'city' => 'Royal Oak', 'state' => 'MI', 'postal' => 48046)),
			'ship-to' => array('given' => 'Chris', 'family' => 'Dumars', 'address' => array('lines' => "458 Walkman Dr.\nSuite #292\n", 'city' => 'Royal Oak', 'state' => 'MI', 'postal' => 48046)),
			'product' => array(
				0 => array('sku' => 'BL394D', 'quantity' => 4, 'description' => 'Basketball', 'price' => 450),
				1 => Array('sku' => 'BL4438H', 'quantity' => 1, 'description' => 'Super Hoop', 'price' => 2392)
			),
			'tax' => 251.42,
			'total' => 4473682,
			'comments' => 'Late afternoon is best. Backup contact is Nancy Billsmer @ 338-4338.'
		),
		'28.yml' => array(
			0 => array('Time' => 1006545702, 'User' => 'ed', 'Warning' => 'This is an error message for the log file'),
			1 => array('Time' => 1006545751, 'User' => 'ed', 'Warning' => 'A slightly different error message.'),
			2 => array('Date' => 1006545797, 'User' => 'ed', 'Fatal' => 'Unknown variable "bar"', 'Stack' => array(
				0 => array('file' => 'TopClass.py', 'line' => 23, 'code' => "x = MoreObject(\"345\\n\")\n"),
				1 => array('file' => 'MoreClass.py', 'line' => 58, 'code' => 'foo = bar'))
			)
		)
	);

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new YAMLReader;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Moss\component\reader\YAMLReader::read
	 */
	public function testRead() {
		foreach($this->files as $file => $result) {
			$this->assertEquals($result, $this->object->read(__DIR__ . '/' . $file, false), 'Error in ' . $file);
		}
	}

	/**
	 * @covers Moss\component\reader\YAMLReader::parse
	 */
	public function testParse() {
		foreach($this->files as $file => $result) {
			$content = file_get_contents(__DIR__ . '/' . $file);
			$this->assertEquals($result, $this->object->parse($content), 'Error in ' . $file);
		}
	}
}
